### ISSUE TITLE
Can TrapTagger export bounding boxes?

### ISSUE THREAD

**Issue by VLucet** [WildEyeConservation/TrapTagger#2]
Congrats on what could be the best platform for processing CT images out there. I have asked to register and cannot wait to try it. 

I was wondering whether TrapTagger is able to export the bounding boxes that MD generates, and whether it can export into formats such as [COCO CT](https://github.com/Microsoft/CameraTraps/blob/main/data_management/README.md#coco-cameratraps-format) or [Camtrap DP](https://github.com/tdwg/camtrap-dp)

**Comment by NicholasOsner** [comment]
Since Val and I communicated directly over email, I never got around to responding here. Historically, TrapTagger did not support the export of bounding boxes simply due to the fact that nobody had asked for that feature.

I have now added both a dedicated COCO export, along with the ability to export bounding boxes in the csv generator.
